spring:
  profiles:
    active: batch,local
    group:
      local:
        - db
        - redis
        - cache
        - member
      dev:
        - db
        - redis
        - cache
        - member
      prod:
        - db
        - redis
        - cache
        - member

---

spring:
  application:
    name: batch

---

spring:
  config:
    activate:
      on-profile: local,dev
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    io.github.harryjhin: DEBUG
    root: info
    sql: debug
    web: debug

---