spring:
  profiles:
    active: api,local
    group:
      local:
        - db
        - redis
        - cache
        - member
      dev:
        - db
        - redis
        - cache
        - member
      prod:
        - db
        - redis
        - cache
        - member
  messages:
    basename: i18n/message
    encoding: UTF-8

---

spring:
  application:
    name: api

---

spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: local,dev

logging:
  level:
    root: INFO
    io.github.harryjhin: TRACE

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    io.github.harryjhin: WARN