spring:
  application:
    name: kotlin-spring
  profiles:
    active: api,local
    group:
      local:
        - db
        - redis
        - cache
        - member
      dev:
        - db
        - redis
        - cache
        - member
      prod:
        - db
        - redis
        - cache
        - member

---

spring:
  config:
    activate:
      on-profile: local,dev

logging:
  level:
    io.github.harryjhin: DEBUG
    root: info
    sql: debug

---