spring:
  application:
    name: kotlin-spring
  profiles:
    active: local
  config:
    import:
      - classpath:application-datasource.yml

logging:
  level:
    io.github.harryjhin: DEBUG
    root: info
    sql: debug
#logging.pattern.console=%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}){} %clr(${PID:}){magenta} %clr(--- %esb(){APPLICATION_NAME}%esb{APPLICATION_GROUP}[%15.15t] ${LOG_CORRELATION_PATTERN:-}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
