services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kotlin-spring
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on", "-c", "log_disconnections=on"]
  redis:
    container_name: redis
    image: redis:7.0.15-alpine
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.16.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TZ: Asia/Seoul
  logstash:
    container_name: logstash
    image: logstash:8.16.0
    ports:
      - "5044:5044"
    environment:
      TZ: Asia/Seoul
  kibana:
    container_name: kibana
    image: kibana:8.16.0
    ports:
      - "5601:5601"
    environment:
      TZ: Asia/Seoul
  filebeat:
    container_name: filebeat
    image: elastic/filebeat:8.16.0
    environment:
      TZ: Asia/Seoul
