datasource:
  read-only:
    url: ${RO_DATABASE_URL}
    username: ${RO_DATABASE_USERNAME}
    password: ${RO_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  read-write:
    url: ${RW_DATABASE_URL}
    username: ${RW_DATABASE_USERNAME}
    password: ${RW_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

---

spring:
  config:
    activate:
      on-profile: local,dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
    open-in-view: false
