spring:
  config:
    activate:
      on-profile: local,dev,prod
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

datasource:
  read-only:
    url: ${RO_DATABASE_URL}
    username: ${RO_DATABASE_USERNAME}
    password: ${RO_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  read-write:
    url: ${RW_DATABASE_URL}
    username: ${RW_DATABASE_USERNAME}
    password: ${RW_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

---

